spring.application.name=ecopark-bicycle-parking

spring.datasource.url=jdbc:mysql://localhost:3306/ecopark_bike?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update