# Đảm bảo đúng tên database ecopark_bike đã thấy trong phpMyAdmin
spring.datasource.url=jdbc:mysql://localhost:3306/ecopark_bike?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Quan trọng: Cho phép Hibernate tự cập nhật bảng khi bạn đổi code User.java
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true